name: Test CLI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: snok/install-poetry@v1
        with:
          version: 2.2.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies using poetry
        run: poetry install --no-interaction --no-root
      - name: Install project
        run: poetry install --no-interaction
      - name: Lint with Ruff
        run: poetry run ruff check
        continue-on-error: true
      - name: Test with pytest
        run: poetry run pytest
